# Generated by Django 2.0 on 2020-01-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Course_name', models.CharField(max_length=30)),
                ('Faculty', models.CharField(max_length=30)),
                ('Duration', models.TextField(max_length=10)),
                ('course_content', models.FileField(upload_to='contents')),
            ],
        ),
    ]
