# Generated by Django 2.0 on 2020-01-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoSoft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Duration',
            field=models.CharField(max_length=10),
        ),
    ]
