# Generated by Django 2.0 on 2020-01-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoSoft', '0003_feedbackdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.BigIntegerField()),
                ('comments', models.TextField(max_length=100)),
                ('date', models.DateTimeField(max_length=30)),
            ],
        ),
    ]
